### ISSUE TITLE
[Bug Report] The first line of the distro logo not being displayed.

### ISSUE THREAD

**Issue by proptrader33** [alba4k/albafetch#102]
**Describe the bug**
The first line of the distro logo is not being displayed.

**Expected behavior**
The first line of the distro logo is expected to be displayed.

**Screenshots**
[a screenshot showing the distro logo in albafetch in juxtaposition to neofetch](https://imgur.com/a/2I1S87G)

**Desktop (please complete the following information):**
 - OS: debian
 - Terminal gnome-terminal

**Possibly relevant config lines:**
 - I did not change any config files.

**Additional context**
I really like this program. Would love to see this bug fixed. Thank you!

**Comment by alba4k** [comment]
good catch, thanks!
