### ISSUE TITLE
[Bug Report] Build needs C99 (at least)

### ISSUE THREAD

**Issue by barracuda156** [alba4k/albafetch#115]
Also looks like we need `-std=c99` or `-std=gnu99` (assuming C99 is sufficient), since otherwise:
```
[3/64] Compiling C object albafetch.p/src_utils.c.o
FAILED: albafetch.p/src_utils.c.o 
/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_albafetch/albafetch/work/compwrap/cc/usr/bin/gcc-4.2 -Ialbafetch.p -I. -I.. -I/opt/local/include -Wall -Winvalid-pch -Wextra -pedantic -O0 -g -Os -arch ppc -Wall -Wextra -Os -MD -MQ albafetch.p/src_utils.c.o -MF albafetch.p/src_utils.c.o.d -o albafetch.p/src_utils.c.o -c ../src/utils.c
In file included from ../src/utils.c:8:
../src/logos.h:8:35: warning: C++ style comments are not allowed in ISO C90
../src/logos.h:8:35: warning: (this will be reported only once per input file)
In file included from ../src/utils.c:9:
../src/utils.h:112:1: warning: C++ style comments are not allowed in ISO C90
../src/utils.h:112:1: warning: (this will be reported only once per input file)
../src/utils.c:11:1: warning: C++ style comments are not allowed in ISO C90
../src/utils.c:11:1: warning: (this will be reported only once per input file)
../src/utils.c: In function ‘file_to_logo’:
../src/utils.c:28: warning: ISO C90 forbids mixed declarations and code
../src/utils.c:47: warning: ISO C90 forbids mixed declarations and code
../src/utils.c:59: error: ‘for’ loop initial declaration used outside C99 mode
../src/utils.c: In function ‘add_module’:
../src/utils.c:109: error: ‘for’ loop initial declaration used outside C99 mode
../src/utils.c: In function ‘get_logo_line’:
../src/utils.c:146: error: ‘for’ loop initial declaration used outside C99 mode
../src/utils.c: In function ‘print_line’:
../src/utils.c:156: warning: ISO C90 forbids mixed declarations and code
../src/utils.c:159: error: ‘for’ loop initial declaration used outside C99 mode
../src/utils.c: In function ‘parse_config_str’:
../src/utils.c:226: warning: ISO C90 forbids mixed declarations and code
../src/utils.c: In function ‘parse_config_int’:
../src/utils.c:266: warning: ISO C90 forbids mixed declarations and code
../src/utils.c: In function ‘parse_config’:
../src/utils.c:344: warning: ISO C90 forbids mixed declarations and code
../src/utils.c:347: warning: ISO C90 forbids mixed declarations and code
../src/utils.c:352: warning: ISO C90 forbids mixed declarations and code
../src/utils.c:364: warning: ISO C90 forbids mixed declarations and code
../src/utils.c:370: warning: ISO C90 forbids mixed declarations and code
../src/utils.c:373: error: ‘for’ loop initial declaration used outside C99 mode
../src/utils.c:382: warning: ISO C90 forbids mixed declarations and code
../src/utils.c:397: error: ‘for’ loop initial declaration used outside C99 mode
../src/utils.c:415: warning: ISO C90 forbids mixed declarations and code
../src/utils.c:446: error: ‘for’ loop initial declaration used outside C99 mode
../src/utils.c:466: warning: ISO C90 forbids mixed declarations and code
../src/utils.c:503: error: redefinition of ‘i’
../src/utils.c:446: error: previous definition of ‘i’ was here
../src/utils.c:503: error: ‘for’ loop initial declaration used outside C99 mode
../src/utils.c:520: warning: ISO C90 forbids mixed declarations and code
../src/utils.c: In function ‘strlen_real’:
../src/utils.c:607: warning: ISO C90 forbids mixed declarations and code
```

**Comment by alba4k** [comment]
Should be fixed with https://github.com/alba4k/albafetch/commit/feb9b513df5568d831d2678f6f1306361f18ab99

also, weird that it warns about redefining i in lines 446 / 503 of utils.c, as that's inside a for loop. I guess that used to be invalid in c90? too young for this lol

**Comment by barracuda156** [comment]
Thank you! I will try building tomorrow once back to the machine.

**Comment by alba4k** [comment]
btw using c99 did not work, I would probably need to define _GNU_SOURCE (gethostname and getline)

using gnu99 is likely just easier

**Comment by barracuda156** [comment]
`getline` is not present in macOS prior to 10.7 btw, but we can use `legacysupport` library to provide it.

**Comment by alba4k** [comment]
maybe make a pr for that, not really breed for my teeth (does this exist in english? idk and idc)

**Comment by alba4k** [comment]
> To use this library within [MacPorts](https://github.com/macports) add the legacysupport PortGroup to the Portfile. This will add the required include paths and libraries to allow the library to do it's magic with most build systems.

Does this mean it's something you need to do on another repo? sorry, really not familiar with the way those ports work. That would mean this issue can be closed, right?

On another note, should I mention https://ports.macports.org/port/albafetch/ in the readme and if so, how?

**Comment by barracuda156** [comment]
MacPorts has a lib to supplement older MacOS with some often-needed features from later SDKs. Usually it is enough to declare a dependency on it in a portfile via portgroup, and it “just works”. Sometimes it is needed to add its flags manually. Used quite often since it’s impractical to convince every upstream to add a dedicated implementation for macOS which lack this or that feature (and perhaps not worth it either).
A drawback is that a given software will only build in MacPorts but not independently from source (on macOS versions which lack some required features). If you care about this, then there is a need for a fallback code when `getline` is unavailable. But realistically speaking, perhaps anyone who may want to build something from source on old macOS is at least aware of MacPorts (and NetBSD’s `pkgsrc`, I think, has its port, pulling in MacPorts’ `legacysupport`).

Sure, you can mention MacPorts as a way to install `albafetch` on MacOS. (In principle, MacPorts may work on non-Apple OS, but it is rather painful and takes a lot of effort. So rather consider it macOS-specific option.)

**Comment by barracuda156** [comment]
P. S. This issue can indeed be closed, since c99 is added and it works as expected.
