### ISSUE TITLE
`true` output on every new line

### ISSUE THREAD

**Issue by ThatOneCalculator** [alba4k/albafetch#18]
I don't think this is intended behavior?

![image](https://user-images.githubusercontent.com/44733677/178391049-4472c15e-3567-4f25-834c-af9a0d487cf3.png)

**Comment by alba4k** [comment]
It was indeed not! Discovered the issue yesterday too in a fedora VM, it's now fixed :)

The changes I made are in those commits:
parse_config_bool() was broken af ([adc6392](https://github.com/alba4k/albafetch/commit/e2a1732f5e34568ffcf7c4199a51b4da92adb811))
prints parent process as shell ([e2a1732](https://github.com/alba4k/albafetch/commit/adc639234329ac36e72fe5acd1a63e51af8df20e))
