### ISSUE TITLE
Screenshot of albafetch output not shown on readme

### ISSUE THREAD

**Issue by spartanatreyu** [alba4k/albafetch#29]

**Comment by alba4k** [comment]
![immagine](https://github.com/alba4k/albafetch/assets/84153269/fe47aa53-88f5-4fce-bdd2-24631f679909)
Are we talking about this image? it's not supposed to show.

That screenshot exists as a demo image for https://github.com/wick3dr0se/open-fetch

**Comment by spartanatreyu** [comment]
What do you mean?

Why would I need to go to another repo to see an example of this repo?

**Comment by alba4k** [comment]
that image only exists because I needed one for that repo and this was where it made more sense to store it

I might add it to the README tho, I just have no idea where to place it lol
